/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'ruslanmikhalev' at '1/13/17 11:35 AM' with Gradle 3.2.1
 *
 * @author ruslanmikhalev, @date 1/13/17 11:35 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
